config/routes.rb
Rails.application.routes.draw do
  resources :shows
  resources :users
  # resources :sessions
  get '/', to: 'users#welcome', as: 'welcome'
  get 'user/delete/:id', to: 'users#destroy', as: 'delete_account'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'logout', to: 'sessions#destroy'
  get '/delete/fav/:id', to: 'favorites#destroy', as: 'delete_fav'
  get '/add/:id', to: 'favorites#add', as: 'add'
  get '/users/favs/:id', to: 'users#favs', as: 'user_favs'
  get '/users/recommended/:id', to:'users#recommended', as: 'user_recommended'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :show
  belongs_to :user
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :show_genres
    has_many :shows, through: :show_genres
end

app/models/show.rb
class Show < ApplicationRecord
    has_many :favorites
    has_many :users, through: :favorites
end

app/models/user.rb
class User < ApplicationRecord
    has_many :favorites
    has_many :shows, through: :favorites
    validates :name, presence: true
    validates :username, presence: true
    validates :username, uniqueness: true
    validates :password, presence: true
    validates :password, confirmation: { case_sensitive: true }
    before_save :downcase_user

    def downcase_user
       self.username.downcase!
    end

    def most_common_value(array)
        #This evaluates the genre array and returns the most liked genres. 
        array.group_by do |genre|
            genre
         end.values.max_by(&:size).first
    end

    def liked_genre
        if self.shows.length > 0
            @genre = self.shows.map{|show| show.genre }.compact
            most_common_value(@genre)
        else
            @reco = nil 
        end 
    end

    def reco_shows
        if liked_genre
            Show.all.find_all{|show| show.genre == self.liked_genre }
        else
            @reco = nil
        end
        
    end



# def most_common_values(array)
#     #This evaluates the genre array and returns the most liked genres. 
#     array.group_by do |genre|
#         genre
#      end.values.max_by(&:size).first
# end

# def u2
#     @favs = Favorite.all.find_all{|favorite| favorite.show.genre = self.liked_genre }
#     most_common_values(@favs).show.title
# end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    def add
        Favorite.create(show_id: params[:id].to_i, user_id: session[:user_id])
        redirect_to user_favs_path(session[:user_id])
    end

    def destroy 
        Favorite.find_by(show_id: params[:id].to_i, user_id: session[:user_id]).destroy
        redirect_to user_favs_path(session[:user_id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        render :new, layout: 'layouts/login'
    end

    def create  
        @user = User.find_by(username: params[:session][:username].downcase)
        if @user && @user.password == (params[:session][:password])
            session[:user_id] = @user.id
            flash[:success] = "You have successfully logged in"
            redirect_to user_path(@user)
        else 
            flash[:danger] = "NOPE!"
            render :new, layout: 'layouts/login'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:success] = "You have logged out"
        redirect_to login_path
    end
end
 

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
    
    def index 
        redirect_to( login_path flash[:danger] = "Login reduired") unless session.include? :user_id
        @shows = Show.all
    end

    def show 
        redirect_to( login_path flash[:danger] = "Login reduired") unless session.include? :user_id
        @show = Show.find(params[:id])
        
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find, only: [:show, :edit, :update, :favs, :destroy, :edit]

   def new 
       @user = User.new
       render :new, layout: 'layouts/login'
   end

   def welcome
      render :welcome , layout: 'layouts/welcome'
   end

   def create
      @user = User.new(users_params)
      if @user.save
        redirect_to login_path, notice: "CREATED ACCOUNT"
        else 
        render :new, layout: 'layouts/login'
      end 
   end 
   
   def show
    redirect_to( login_path flash[:danger] = "Login reduired") unless session.include? :user_id
   end

   def favs
    redirect_to( login_path flash[:danger] = "Login reduired") unless session.include? :user_id
    @user = User.find(params[:id])
    @shows = @user.shows
    
   end

   def recommended
    redirect_to( login_path flash[:danger] = "Login reduired") unless session.include? :user_id
    @user = User.find(session[:user_id])
    @shows = @user.shows
   end

   def edit
    redirect_to( login_path flash[:danger] = "Login reduired") unless session.include? :user_id
   end

   def update 
    redirect_to( login_path flash[:danger] = "Login reduired") unless session.include? :user_id
    if @user.update(users_params)
      redirect_to login_path, notice: "ACCOUNT UPDATE"
      else 
      render :new
    end 
   end

   def destroy 
      redirect_to( login_path flash[:danger] = "Login reduired") unless session.include? :user_id
      @user.favorites.destroy
      @user.shows.destroy
      session[:user_id] = nil
      if @user.destroy
        redirect_to login_path, notice: "DELETED ACCOUNT"
      else 
        "nope"
      end 
   end

   private 

   def find 
     @user =  User.find(params[:id])
   end

   def users_params
      params.require(:user).permit(:name, :age, :username, :password, :password_confirmation)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorite_helper.rb
module FavoriteHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorite/add.html.erb
<h1><%= @show.title %></h1>
</br>
<img src="<%= @show.image %>">
</br>

app/views/layouts/all.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BingrAppMaster</title>
    <%= csrf_meta_tags %> 
    <%= csp_meta_tag %> 
    <%= stylesheet_link_tag 'all', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Sarabun:800i&display=swap" rel="stylesheet">
    <title>bingr.</title>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
  <a class="navbar-brand" href="<%= user_path(session[:user_id]) %>">Bingr.</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= shows_path %>">Shows <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= user_favs_path(session[:user_id]) %>">Favorites</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= user_recommended_path(session[:user_id]) %>">Recommended Shows</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Settings
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="<%= edit_user_path(session[:user_id]) %>">Edit Account</a>
          <a class="dropdown-item" href="<%= delete_account_path(session[:user_id]) %>"> Delete Account </a>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <a class="btn btn-outline-danger my-2 my-sm-0" href="<%= logout_path %>">Logout</a>
    </form>
    </div>
  </div>
</nav>
    <% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <title>Bingr.</title>
    <%= csrf_meta_tags %> 
    <%= csp_meta_tag %> 
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Archivo+Black|Oswald|Roboto+Condensed&display=swap" rel="stylesheet">
    <title>bingr.</title>
  </head>
<body>
<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
  <a class="navbar-brand"  href="<%= user_path(session[:user_id]) %>">Bingr.</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= shows_path %>">Shows <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= user_favs_path(session[:user_id]) %>">Favorites</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= user_recommended_path(session[:user_id]) %>">Recommended Shows</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Settings
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="<%= edit_user_path(session[:user_id]) %>">Edit Account</a>
          <%#<a class="dropdown-item" href="<%= delete_account_path(session[:user_id])"> Delete Account </a> %>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <a class="btn btn-outline-danger my-2 my-sm-0" href="<%= logout_path %>">Logout</a>
    </form>
    </div>
  </div>
</nav>

    <% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <%= yield %>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BingrAppMaster</title>
    <%= csrf_meta_tags %> 
    <%= csp_meta_tag %> 
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Archivo+Black|Oswald|Roboto+Condensed&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'login', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge"> 
    <title>bingr.</title>
  </head>

  <body>
    <% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>
    <%= yield %>
  </body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <body>
   <link href="https://fonts.googleapis.com/css?family=Archivo+Black|Oswald|Roboto+Condensed&display=swap" rel="stylesheet">
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <%= yield %>
  </body>
</html>

app/views/shows/index.html.erb
<br><br><br>
<h1 style='text-align: center; color:gray;'>All Shows</h1>
<ul class="hoverbox">
<li class="li-first">
 <% @shows.each do |show| %>
   <a href="<%= show_path(show)%>"><img src="<%= show.image %>"  alt=" <%= show.title %> "/></a>
    <% end %>
</li>

app/views/shows/show.html.erb
<h1 class="showhead"><%= @show.title %> - <%= @show.genre %></h1>

</br>
<img src="<%= @show.image %>" id="leftImage">

</br>
<div id="rightText">
<h3 id="showText"><%= @show.title %> --- <%= @show.genre %></h3>


<h4 id="showText">Episode Count: <%= @show.episode_count %></h4>

<p id="showText"><%=  strip_tags(@show.desc) %></p>

<% @user = User.find(session[:user_id]) %>
<% @fav = @user.favorites.find_by(show_id: @show.id)  %>
<% if @fav %>
   <a style="text-decoration : none"  href="<%= delete_fav_path(@show) %>"><button class="button1">Remove Show from Favorites</button></a> </h1>
<% else %>
    <a style="text-decoration : none"  href="<%= add_path(@show) %>"><button class="button1">Add To Favorites</button></a> </h1>
<% end %>
<br>
<a style="text-decoration : none"  href="<%= shows_path %>"><button class="button2">All shows</button></a> </h1>

app/views/users/edit.html.erb
<div class="sidenav">
            
      </div>
      <div class="main">
         <div class="col-md-6 col-sm-12">
            <div class="login-form">
               <div class="form-group">
                  <h1 align="center">EDIT ACCOUNT</h1>
                    <%= form_for @user do |f| %>
                        <%= f.label :NAME %>
                        <%= f.text_field :name, class: "form-control", placeholder: "ENTER NAME", autofocus: true %>
                        <%= f.label :AGE%>
                        <%= f.text_field :age, class: "form-control", placeholder: "ENTER AGE", autofocus: true %>
                        <%= f.label :USERNAME %>
                       <%= f.text_field :username, class: "form-control", placeholder: "PREFERRED USERNAME", autofocus: true %>
                        <%= f.label :PASSWORD %>
                        <%= f.password_field :password, class: "form-control", placeholder: "PREFERRED PASSWORD", autofocus: true %>
                        <%= f.label :"Confirm Password" %>
                        <%= f.password_field :password_confirmation, class: "form-control", placeholder: "PREFERRED PASSWORD", autofocus: true %>
                      <button class= "button1" type='submit'>Edit Account</button>
                  <%end %>
             </div>
         </div>
      </div>
 </div>

<%# NEEDS TO CONFIRM CURRENT PASSWORD BEFORE CHANGING %>

app/views/users/favs.html.erb
<br>
<br>
<br>
<h1 style='text-align: center; color:gray;'><%= @user.name.capitalize %>'s Favorites </h1>

<ul class="hoverbox">
  <li class="li-first">
    <% @shows.each do |show| %>
    <a href="<%= show_path(show)%>"><img src="<%= show.image %>"/></a>
    <% end  %>
</ul>

app/views/users/index.html.erb
<h1>Welcome!</h1>
<ul>
Please Create an Account now!
</br>
<%= link_to  "CREATE ACCOUNT", new_user_path%>
</ul>

app/views/users/new.html.erb
<div class="sidenav">
            <h2>Bingr.</h2>
            <h3>your path to binging.</h3>
      </div>
      <div class="main">
         <div class="col-md-6 col-sm-12">
            <div class="login-form">
               <div class="form-group">
                  <h1 align="center">CREATE ACCOUNT</h1>
                    <%= form_for @user do |f| %>
                        <%= f.label :NAME %>
                        <%= f.text_field :name, class: "form-control", placeholder: "ENTER NAME", autofocus: true %>
                        <%= f.label :AGE%>
                        <%= f.text_field :age, class: "form-control", placeholder: "ENTER AGE", autofocus: true %>
                        <%= f.label :USERNAME %>
                       <%= f.text_field :username, class: "form-control", placeholder: "PREFERRED USERNAME", autofocus: true %>
                        <%= f.label :PASSWORD %>
                        <%= f.password_field :password, class: "form-control", placeholder: "PREFERRED PASSWORD", autofocus: true %>
                        <%= f.label :"Confirm Password" %>
                        <%= f.password_field :password_confirmation, class: "form-control", placeholder: "PREFERRED PASSWORD", autofocus: true %>
                      <button class= "button1" type='submit'>Create Account</button>
                     <a href="<%= login_path %>"><button class= "button2" >Login Now</button></a>
                  <%end %>
             </div>
         </div>
      </div>
 </div>

app/views/users/recommended.html.erb
<br><br><br>
<h1 style='text-align: center; color:gray;'><%= @user.name.capitalize %>'s Recommended Shows: </h1>
<ul class="hoverbox">
  <li class="li-first">
  <% if @user.reco_shows%>
<% @user.reco_shows.each do |show|%>
    <a href="<%= show_path(show)%>"><img src="<%= show.image %>"  alt=" <%= show.title %> "/></a>
<% end %>
<% else %> 
<h3>We can't recommend any shows at this time</h3>
<% end %>
</li> 
</ul>

app/views/users/show.html.erb
<%# <%= link_to 'logout', logout_path %>
<%#<h1> Welcome <%= @user.name.capitalize %>
<%#<h3><%= link_to "SEE MY FAVS",user_favs_path  %>
<%#<h3><%= link_to "DESTROY ACCOUNT",delete_account_path %>
<%#<h3><%= link_to "EDIT ACCOUNT", edit_user_path%>
<%# <h3><%= link_to "recommended", user_recommended_path %>
</br>
</br>
</br>
 <h1>Welcome <%= @user.name %></h1>
<div class="container">
<% if @user.shows.count > 0  %>
</br>
        <h2> recently favorited: <a style="text-decoration : none"  href="<%= user_favs_path %>"><button>All Favorites</button></a> </h2>
       </br>
        <% @shows = @user.shows.last(5) %>
            <% @shows.each do |show|%>
                 <a href="<%= show_path(show)%>"><img src="<%= show.image %>"/></a>
             <% end %>
             </br>m 
             </br>
         <h2>All Recommendation</h2>  
       </br>
       <div class="container">
        <% @reco = @user.reco_shows[0..4] %>
            <% @reco.each do |show| %>
            <img src="<%= show.image %>"/>
            <% end %>
        </div>
<% else %>
    <h1>Welcome! <%= @user.name %> </h1>
    <br>
    <h1>To get started, Click the shows page and add some shows to your favorites! </h1>
    <h2>We recommend shows, based on your favorites. Everytime you add a new show our system, we 
    automatically find shows based on your favorites!</h2>
    <h3>Happy Binging!</h3>
    </br>
    </div>
    <div class="container"
    <h1><a style="text-decoration : none" href="<%= shows_path %>"><button class="button1" >All Shows</button></a> </h1>
    <div class="container">
    <% Show.all[0..7].each do |show| %>
    <a href="<%= show_path(show)%>"><img src="<%= show.image %>"/></a>
    <% end %>
     </div>
<% end %>

app/views/users/welcome.html.erb
   <%= stylesheet_link_tag "welcome", media: "all", "data-turbolinks-track" => true %>  

        <div class="bigImage">
            <div class="container" >
                <a class= "button1" href="<%= login_path %>">Login</a>
                <a class= "button2" href="<%= new_user_path %>">Create Account</a>
            </div>
        </div>

 